// apps/nativescript-vue/src/components/Home.vue
<script lang="ts" setup>
import { Color } from "@nativescript/core";
import { setupLamp, ISwiftLamp } from '@lava/nativescript-lamp';
setupLamp();

const data: ISwiftLamp = {
  gradientTopColor: new Color("#64b788").ios,
  gradientMiddleColor: new Color("#64b788").ios,
  gradientBottomColor: new Color("#35475c").ios,
};
</script>

<template>
  <Frame>
    <Page>
      <GridLayout class="bg-black">

        <SwiftUI swiftId="lavaLamp" :data="data">
        </SwiftUI>

        <Image src="https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Vue.js_Logo_2.svg/1024px-Vue.js_Logo_2.svg.png?20170919082558" class="logo"/>
      </GridLayout>
    </Page>
  </Frame>
</template>

// apps/nativescript-angular/src/app/home.component.ts
import { Component } from "@angular/core";
import { Color } from "@nativescript/core";
import { setupLamp, ISwiftLamp } from '@lava/nativescript-lamp';
setupLamp();

@Component({
  selector: "ns-home",
  templateUrl: "./home.component.html",
})
export class HomeComponent {
  data: ISwiftLamp = {
    gradientTopColor: new Color('#b32535').ios,
    gradientMiddleColor: new Color('#bd2b39').ios,
    gradientBottomColor: new Color('#bd2b39').ios,
  };;
}

<GridLayout class="bg-black">

  <SwiftUI swiftId="lavaLamp" [data]="data">
  </SwiftUI>

  <Image src="https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Angular_full_color_logo.svg/2048px-Angular_full_color_logo.svg.png" class="logo"></Image>
</GridLayout>
