// apps/nativescript-vue/src/components/Home.vue
<script lang="ts" setup>
import { Color } from "@nativescript/core";
import { setupLamp, ISwiftLamp } from '@lava/nativescript-lamp';
setupLamp();

const data: ISwiftLamp = {
  gradientTopColor: new Color("#64b788").ios,
  gradientMiddleColor: new Color("#64b788").ios,
  gradientBottomColor: new Color("#35475c").ios,
};
</script>

<template>
  <Frame>
    <Page>
      <GridLayout class="bg-black">

        <SwiftUI swiftId="lavaLamp" :data="data">
        </SwiftUI>

        <Image src="https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Vue.js_Logo_2.svg/1024px-Vue.js_Logo_2.svg.png?20170919082558" class="logo"/>
      </GridLayout>
    </Page>
  </Frame>
</template>

// apps/nativescript-svelte/src/components/Home.svelte
<page>
    <gridLayout class="bg-black">
        <swiftUI swiftId="lavaLamp" data="{data}"/>
        <image src="https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Svelte_Logo.svg/996px-Svelte_Logo.svg.png?20191219133350" class="logo"></image>
    </gridLayout>
</page>

<script lang="ts">
    import { ISwiftLamp } from '@lava/nativescript-lamp';
    import { Color } from '@nativescript/core';

    const data: ISwiftLamp = {
        gradientTopColor: new Color('#eb4e27').ios,
        gradientMiddleColor: new Color('#eb4e27').ios,
        gradientBottomColor: new Color('#fff').ios,
    };
</script>
